/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Airports.h"

bool_t
xdr_nearestairportnames (XDR *xdrs, nearestairportnames *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_coordinates_airport (XDR *xdrs, coordinates_airport *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}
