/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Airports.h"

bool_t
xdr_nearestairportnames (XDR *xdrs, nearestairportnames *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_coordinates_airport (XDR *xdrs, coordinates_airport *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}
bool_t
xdr_airports_server_ret (XDR *xdrs, airports_server_ret *objp)
{
        register int32_t *buf;

         if (!xdr_int (xdrs, &objp->err))
                 return FALSE;
        switch (objp->err) {
        case 0:
                 if (!xdr_nearestairportnames (xdrs, &objp->airports_server_ret_u.airports))
                         return FALSE;
                break;
        case 1:
                break;
        default:
                return FALSE;
        }
        return TRUE;
}
      
