/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 512

typedef char *nearestairportnames;

struct coordinates_airport {
        double lat;
        double lon;
};

typedef struct coordinates_airport coordinates_airport;
struct airports_server_ret {
        int err;
        union {
                nearestairportnames airports;
        } airports_server_ret_u;
};
typedef struct airports_server_ret airports_server_ret;


#define AIRPORT_PROG 0x37777747
#define AIRPORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_FIVE_NEAREST_AIRPORTS 1
extern  airports_server_ret * get_five_nearest_airports_1(coordinates_airport *, CLIENT *);
extern  airports_server_ret * get_five_nearest_airports_1_svc(coordinates_airport *, struct svc_req *);
extern int airport_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);


#else /* K&R C */
#define GET_FIVE_NEAREST_AIRPORTS 1
extern  airports_server_ret * get_five_nearest_airports_1();
extern  airports_server_ret * get_five_nearest_airports_1_svc();
extern int airport_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nearestairportnames (XDR *, nearestairportnames*);
extern  bool_t xdr_coordinates_airport (XDR *, coordinates_airport*);
extern  bool_t xdr_airports_server_ret (XDR *, airports_server_ret*);
#else /* K&R C */
extern bool_t xdr_nearestairportnames ();
extern bool_t xdr_coordinates_airport ();
extern bool_t xdr_airports_server_ret ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
