/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef char *airportname;

typedef char *nearestairports;

struct coordinates_airport {
        double lat;
        double lon;
};

typedef struct coordinates_airport coordinates_airport;

#define AIRPORT_PROG 0x37777747
#define AIRPORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_FIVE_NEAREST_AIRPORTS 1
extern  nearestairports * get_five_nearest_airports_1(coordinates_airport *, CLIENT *);
extern  nearestairports * get_five_nearest_airports_1_svc(coordinates_airport *, struct svc_req *);
extern int airport_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_FIVE_NEAREST_AIRPORTS 1
extern  nearestairports * get_five_nearest_airports_1();
extern  nearestairports * get_five_nearest_airports_1_svc();
extern int airport_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_airportname (XDR *, airportname*);
extern  bool_t xdr_nearestairports (XDR *, nearestairports*);
extern  bool_t xdr_coordinates_airport (XDR *, coordinates_airport*);

#else /* K&R C */
extern bool_t xdr_airportname ();
extern bool_t xdr_nearestairports ();
extern bool_t xdr_coordinates_airport ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
