/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>
#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255


typedef char *airportname;

typedef char *nearestairports;

#define PLACES_PROG 0x37777735
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_COORDINATES 1
extern  nearestairports * get_coordinates_1(airportname *, CLIENT *);
extern  nearestairports * get_coordinates_1_svc(airportname *, struct svc_req *);

extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_COORDINATES 1
extern  nearestairports * get_coordinates_1();
extern  nearestairports * get_coordinates_1_svc();

extern int places_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_airportname (XDR *, airportname*);
extern  bool_t xdr_nearestairports (XDR *, nearestairports*);
#else /* K&R C */
extern bool_t xdr_airportname ();
extern bool_t xdr_nearestairports ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
