/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Places.h"
#include "file_proc.h"
#include <iostream>
#include "Airports.h"
using namespace std;

struct coordinates
{
	double lat;
	double lon;
};
static char* toChar(string str){
  char *ch=new char[str.size()+1];
  ch[str.size()]=0;
  memcpy(ch,str.c_str(),str.size());
  return ch;
}
airports_ret* 
get_coordinates_1_svc(places_input *argp, struct svc_req *rqstp)
{

	static coordinates result ;
	static airports_ret airportnames;
	places_input inputs;
	inputs.apname = argp->apname;
	inputs.hostname = argp->hostname;
	string s = inputs.apname;
					
	/* strip designation*/
	stripDesignation(s);	/* shoudld do nothing*/
	
	/* do search*/
	Coord xy(360,360); 		/* this is where coordinate values will be returned*/
	int res = db->find(s, xy);	
	/* value of res explains the result:*/
 	/* if not found (res <0), return NULL*/ 
	/* else if found (res >=0), call airports fxn ...*/
	
	if(res <0)
	{
	airportnames.err=1;
	return &airportnames;
	}

	else
	{
	
        result.lat = xy.lat;
        result.lon = xy.lon;
	
	}

	
	
	/* return-fwd KNN results*/
	 CLIENT *clnt;
        coordinates_airport  points;
	airports_server_ret *nearestnames;
	 
        points.lat = result.lat;
        points.lon = result.lon;


        #ifndef DEBUG
        clnt = clnt_create (inputs.hostname, AIRPORT_PROG, AIRPORT_VERS, "tcp");
        if (clnt == NULL) {
                clnt_pcreateerror (inputs.hostname);
                exit (1);
        }
        #endif  /* DEBUG */
        
        nearestnames = get_five_nearest_airports_1(&points, clnt);
	 if (nearestnames == (airports_server_ret *) NULL) {
                clnt_perror (clnt, "call failed");
        }
        #ifndef DEBUG
        clnt_destroy (clnt);
        #endif   /* DEBUG */
	      
	
	nearestairportnames output_from_airport =nearestnames->airports_server_ret_u.airports;
	string sss = output_from_airport;
	nearestairports nap;
	nap =(nearestairports)malloc(sizeof(output_from_airport));
	nap = output_from_airport;
        airportnames.airports_ret_u.airports = nap;
        airportnames.err = 0;
        return &airportnames;

}

