/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "Places.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

coordinates *
get_coordinates_1(airportname *argp, CLIENT *clnt)
{
	static coordinates  clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_COORDINATES,
		(xdrproc_t) xdr_airportname, (caddr_t) argp,
		(xdrproc_t) xdr_nearestairports, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nearestairports *
get_nearest_airports_1(coordinates *argp, CLIENT *clnt)
{
	static nearestairports clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_NEAREST_AIRPORTS,
		(xdrproc_t) xdr_coordinates, (caddr_t) argp,
		(xdrproc_t) xdr_nearestairports, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
