/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "Places.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

NearestAirports *
get_airports_1(LocationArgs *argp, CLIENT *clnt)
{
	static NearestAirports clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_AIRPORTS,
		(xdrproc_t) xdr_LocationArgs, (caddr_t) argp,
		(xdrproc_t) xdr_NearestAirports, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
