/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Places.h"

bool_t
xdr_LocationName (XDR *xdrs, LocationName *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_NAME_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StateName (XDR *xdrs, StateName *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, STATE_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NearestAirports (XDR *xdrs, NearestAirports *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_RES_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LocationArgs (XDR *xdrs, LocationArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_LocationName (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_StateName (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}
