/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Places.h"
#include <string>
#include <cstring>
#include "file_proc.h"

NearestAirports *
get_airports_1_svc(LocationArgs *argp, struct svc_req *rqstp)
{
	static NearestAirports  result;

	/** server code here insert */
	/* free previous result */
    xdr_free((xdrproc_t)xdr_NearestAirports, (char *)&result);
	
	/* process input arguments*/
	std::string name = argp->state;
	name.append(argp->name);
	stripDesignation(name);
	 
	/* search db */ 
	Coord xy(360,360);    /* struct to return into*/
	int ret_code = db->find(name, xy);
	
	/* interpret results */
	std::string s_res;
	if (ret_code < 0){
		s_res = "Location not found";
	}
	else {
		s_res = "Location: (";
		s_res+= std::to_string(xy.lat)+","+std::to_string(xy.lon)+")"; 
	}
	
	/* allocate memory! */
	result = (NearestAirports)malloc(sizeof(char)*(s_res.length()+1));
	std::strcpy (result, s_res.c_str());
	/** end server code insert */ 

	return &result;
}
