/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Places.h"


void
places_prog_1(char *host, char *city, char *state)
{
	CLIENT *clnt;
	NearestAirports  *result_1;
	LocationArgs  get_airports_1_arg;
	/** client code insert*/
		/* assign argument struct values*/
		get_airports_1_arg.name = city;
		get_airports_1_arg.state = state;		
	/** end client code instert*/

#ifndef	DEBUG
	clnt = clnt_create (host, PLACES_PROG, PLACES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_airports_1(&get_airports_1_arg, clnt);
	if (result_1 == (NearestAirports *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	/** client code insert*/
		/* print out results */
		printf("%s\n", *result_1);
		
		/* free result memory */
		xdr_free((xdrproc_t)xdr_NearestAirports, (char*)result_1);
	/** end client code instert*/	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *city, *state;

	/* parse arguments from command line*/
	if (argc < 4) {
		printf ("usage: %s server_host city state\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	city = argv[2];
	state = argv[3];
	
	/* call program */
	places_prog_1 (host, city, state);
exit (0);
}
