/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Places.h"
#include <string>
#include <cstring>

NearestAirports *
get_airports_1_svc(LocationArgs *argp, struct svc_req *rqstp)
{
	static NearestAirports  result;

	/** server code here insert */
	/* free previous result */
    xdr_free((xdrproc_t)xdr_NearestAirports, (char *)&result);
		
	std::string name = argp->state;
	name.append(argp->name);
	 
	name.append(std::to_string(name.length()));
	
	/* allocate memory! */
	result = (NearestAirports)malloc(sizeof(char)*(name.length()+1));
	std::strcpy (result, name.c_str());
	/** end server code insert */ 

	return &result;
}
