/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_RES_LEN 255
#define MAX_NAME_LEN 60
#define STATE_LEN 2

typedef char *LocationName;

typedef char *StateName;

typedef char *NearestAirports;

struct LocationArgs {
	LocationName name;
	StateName state;
};
typedef struct LocationArgs LocationArgs;

#define PLACES_PROG 0x37777778
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_AIRPORTS 1
extern  NearestAirports * get_airports_1(LocationArgs *, CLIENT *);
extern  NearestAirports * get_airports_1_svc(LocationArgs *, struct svc_req *);
extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_AIRPORTS 1
extern  NearestAirports * get_airports_1();
extern  NearestAirports * get_airports_1_svc();
extern int places_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_LocationName (XDR *, LocationName*);
extern  bool_t xdr_StateName (XDR *, StateName*);
extern  bool_t xdr_NearestAirports (XDR *, NearestAirports*);
extern  bool_t xdr_LocationArgs (XDR *, LocationArgs*);

#else /* K&R C */
extern bool_t xdr_LocationName ();
extern bool_t xdr_StateName ();
extern bool_t xdr_NearestAirports ();
extern bool_t xdr_LocationArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
